name: FDA Drug Approvals Scraper

on:
  # Run every day at 9 AM UTC
  schedule:
    - cron: '0 9 * * *'
  
  # Allow manual triggering - THIS IS IMPORTANT
  workflow_dispatch:
  
  # Run on push to main branch (for testing)
  push:
    branches: [ main ]

jobs:
  scrape-fda-approvals:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run FDA scraper
      env:
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        python fda_scraper.py 
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
     with:
     name: my-artifact
     path: path/to/files
          *.log
          *.txt
